[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback (toutes les routes -> index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Éviter le cache du Service Worker (important pour les updates)
[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

# Cache agressif des assets fingerprintés (Vite) et des icônes PWA
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Manifest PWA (cache léger) + type explicite
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "public, max-age=3600"

# index.html : pas de cache pour prendre les nouvelles versions
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# En-têtes de sécurité de base (non bloquants pour les APIs navigateur)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
